version: "3"

services:
  db:
    image: postgres:12
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fondeadora
      - POSTGRES_USER=fondeadora
      - POSTGRES_PASSWORD=fondeadora
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  data:
